### PR TITLE
Fix creating wls_server with no arguments

### PR DESCRIPTION
**Pull request by alexjfisher**
Check arguments isn't nil before calling 'join' on it.
Fixes following error when creating wls_server...

```
puppet apply -e 'wls_server{"default/test": ensure => present, machine => "LocalMachine"}'

'Error: /Stage[main]/Main/Wls_server[default/test]/ensure: change from absent to present failed: Could not set 'present' on ensure: undefined method `join' for nil:NilClass in 1'
```

### CODE REVIEW

**Comment by alexjfisher** [comment]
Apologies for the regression caused by https://github.com/biemond/biemond-orawls/pull/259
